"""Email delivery boundary with an optional bounded SMTP transport."""

from __future__ import annotations

import asyncio
import json
import smtplib
import ssl
from email.message import EmailMessage
from typing import Protocol

from app.models import NotificationEvent
from app.notifications.base import DeliveryResult


class EmailTransport(Protocol):
    async def send_message(
        self, message: EmailMessage, *, idempotency_key: str
    ) -> DeliveryResult:
        """Perform one attempt with explicit timeout; return classified failure without secrets."""
        ...


class SmtpTransport:
    """One bounded SMTP attempt.

    Delivery idempotency is represented by the stable Message-ID generated by EmailChannel.
    SMTP itself does not provide a universal idempotency primitive, so ambiguous success remains
    at-least-once just like webhook receivers that ignore Idempotency-Key.
    """

    def __init__(
        self,
        *,
        host: str,
        port: int = 587,
        username: str | None = None,
        password: str | None = None,
        starttls: bool = True,
        timeout_seconds: float = 10.0,
    ) -> None:
        if not host.strip():
            raise ValueError("SMTP host is required")
        if not 1 <= port <= 65535:
            raise ValueError("SMTP port is out of range")
        if timeout_seconds <= 0:
            raise ValueError("SMTP timeout must be positive")
        self._host = host
        self._port = port
        self._username = username
        self._password = password
        self._starttls = starttls
        self._timeout_seconds = timeout_seconds

    async def send_message(
        self, message: EmailMessage, *, idempotency_key: str
    ) -> DeliveryResult:
        del idempotency_key
        return await asyncio.to_thread(self._send_sync, message)

    def _send_sync(self, message: EmailMessage) -> DeliveryResult:
        try:
            with smtplib.SMTP(
                self._host, self._port, timeout=self._timeout_seconds
            ) as client:
                client.ehlo()
                if self._starttls:
                    client.starttls(context=ssl.create_default_context())
                    client.ehlo()
                if self._username is not None:
                    client.login(self._username, self._password or "")
                refused = client.send_message(message)
                if refused:
                    return DeliveryResult(False, error_code="smtp_rejected")
                return DeliveryResult(True)
        except smtplib.SMTPAuthenticationError:
            return DeliveryResult(False, error_code="smtp_auth")
        except smtplib.SMTPRecipientsRefused:
            return DeliveryResult(False, error_code="smtp_rejected")
        except smtplib.SMTPResponseException as error:
            retryable = 400 <= error.smtp_code < 500
            return DeliveryResult(
                False,
                retryable=retryable,
                error_code="smtp_4xx" if retryable else "smtp_5xx",
            )
        except (smtplib.SMTPServerDisconnected, OSError, TimeoutError):
            return DeliveryResult(False, retryable=True, error_code="transport_error")
        except smtplib.SMTPException:
            return DeliveryResult(False, error_code="delivery_failed")


class EmailChannel:
    def __init__(self, transport: EmailTransport, *, sender: str, recipient: str) -> None:
        self._transport, self._sender, self._recipient = transport, sender, recipient

    async def send(self, event: NotificationEvent) -> DeliveryResult:
        message = EmailMessage()
        message["From"], message["To"] = self._sender, self._recipient
        message["Subject"] = f"ProcureDelta: {event.template_key}"
        message["Message-ID"] = f"<{event.dedupe_key}@procure-delta.invalid>"
        message.set_content(json.dumps(event.payload_json, ensure_ascii=False, indent=2))
        return await self._transport.send_message(
            message, idempotency_key=event.dedupe_key
        )
