"""initial procurement persistence schema"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision = '43a24e2f8d9b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_events',
    sa.Column('actor_type', sa.String(length=100), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_profiles',
    sa.Column('owner_user_id', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('synthetic_demo', sa.Boolean(), nullable=False),
    sa.Column('regions', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('industries', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('capabilities', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('certifications', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('employee_band', sa.String(length=100), nullable=True),
    sa.Column('min_contract_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('max_contract_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('excluded_keywords', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_profiles_owner_user_id'), 'company_profiles', ['owner_user_id'], unique=False)
    op.create_table('job_failures',
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('job_key', sa.String(length=255), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_class', sa.String(length=255), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=False),
    sa.Column('last_error_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dead_lettered', sa.Boolean(), nullable=False),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_failures_next_retry_at'), 'job_failures', ['next_retry_at'], unique=False)
    op.create_index('ix_job_failures_dead_lettered_retry', 'job_failures', ['dead_lettered', 'next_retry_at'], unique=False)
    op.create_table('opportunities',
    sa.Column('canonical_key', sa.String(length=255), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('buyer_name', sa.String(length=255), nullable=False),
    sa.Column('procurement_type', sa.String(length=100), nullable=True),
    sa.Column('lifecycle_stage', sa.String(length=100), nullable=True),
    sa.Column('estimated_amount', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_version_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_key')
    )
    op.create_index(op.f('ix_opportunities_closes_at'), 'opportunities', ['closes_at'], unique=False)
    op.create_index(op.f('ix_opportunities_lifecycle_stage'), 'opportunities', ['lifecycle_stage'], unique=False)
    op.create_index(op.f('ix_opportunities_published_at'), 'opportunities', ['published_at'], unique=False)
    op.create_index('ix_opportunities_stage_published', 'opportunities', ['lifecycle_stage', 'published_at'], unique=False)
    op.create_table('source_registry',
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('base_url', sa.String(length=2048), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('polling_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ingest_runs',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('cursor_before', sa.Text(), nullable=True),
    sa.Column('cursor_after', sa.Text(), nullable=True),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_runs_source_id'), 'ingest_runs', ['source_id'], unique=False)
    op.create_table('lifecycle_links',
    sa.Column('parent_opportunity_id', sa.UUID(), nullable=False),
    sa.Column('child_opportunity_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=100), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('link_method', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['child_opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['parent_opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lifecycle_links_child_opportunity_id'), 'lifecycle_links', ['child_opportunity_id'], unique=False)
    op.create_index(op.f('ix_lifecycle_links_parent_opportunity_id'), 'lifecycle_links', ['parent_opportunity_id'], unique=False)
    op.create_table('opportunity_versions',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('effective_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('normalized_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('normalized_sha256', sa.String(length=64), nullable=False),
    sa.Column('extraction_version', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('opportunity_id', 'id', name='uq_opportunity_version_owner'),
    sa.UniqueConstraint('opportunity_id', 'version_number', name='uq_opportunity_version_number')
    )
    op.create_index(op.f('ix_opportunity_versions_opportunity_id'), 'opportunity_versions', ['opportunity_id'], unique=False)
    op.create_foreign_key(
        'fk_opportunity_current_version',
        'opportunities',
        'opportunity_versions',
        ['id', 'current_version_id'],
        ['opportunity_id', 'id'],
    )
    op.create_table('raw_records',
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('payload_sha256', sa.String(length=64), nullable=False),
    sa.Column('http_etag', sa.String(length=255), nullable=True),
    sa.Column('http_last_modified', sa.String(length=255), nullable=True),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source_registry.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'source_record_id', 'payload_sha256', name='uq_raw_record_payload')
    )
    op.create_index(op.f('ix_raw_records_source_id'), 'raw_records', ['source_id'], unique=False)
    op.create_table('watchlists',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'opportunity_id', name='uq_watchlist_user_opportunity')
    )
    op.create_index(op.f('ix_watchlists_opportunity_id'), 'watchlists', ['opportunity_id'], unique=False)
    op.create_table('attachments',
    sa.Column('opportunity_version_id', sa.UUID(), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=False),
    sa.Column('filename', sa.String(length=1024), nullable=False),
    sa.Column('media_type', sa.String(length=255), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('byte_size', sa.Integer(), nullable=True),
    sa.Column('download_status', sa.String(length=50), nullable=False),
    sa.Column('storage_key', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_version_id'], ['opportunity_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attachments_opportunity_version_id'), 'attachments', ['opportunity_version_id'], unique=False)
    op.create_table('eligibility_results',
    sa.Column('company_profile_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_version_id', sa.UUID(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('hard_fail_reasons_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('warnings_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ruleset_version', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_profile_id'], ['company_profiles.id'], ),
    sa.ForeignKeyConstraint(['opportunity_version_id'], ['opportunity_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_eligibility_results_company_profile_id'), 'eligibility_results', ['company_profile_id'], unique=False)
    op.create_index(op.f('ix_eligibility_results_opportunity_version_id'), 'eligibility_results', ['opportunity_version_id'], unique=False)
    op.create_table('opportunity_deltas',
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('from_version_id', sa.UUID(), nullable=False),
    sa.Column('to_version_id', sa.UUID(), nullable=False),
    sa.Column('field_changes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('document_changes_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('impact_level', sa.String(length=20), nullable=False),
    sa.Column('impact_reasons_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['from_version_id'], ['opportunity_versions.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.ForeignKeyConstraint(['to_version_id'], ['opportunity_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_opportunity_deltas_opportunity_id'), 'opportunity_deltas', ['opportunity_id'], unique=False)
    op.create_table('ranking_results',
    sa.Column('company_profile_id', sa.UUID(), nullable=False),
    sa.Column('opportunity_version_id', sa.UUID(), nullable=False),
    sa.Column('lexical_score', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('semantic_score', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('feature_score', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('rerank_score', sa.Numeric(precision=8, scale=5), nullable=True),
    sa.Column('final_score', sa.Numeric(precision=8, scale=5), nullable=False),
    sa.Column('explanation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ranking_version', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['company_profile_id'], ['company_profiles.id'], ),
    sa.ForeignKeyConstraint(['opportunity_version_id'], ['opportunity_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_profile_id', 'opportunity_version_id', 'ranking_version', name='uq_ranking_company_version')
    )
    op.create_index(op.f('ix_ranking_results_company_profile_id'), 'ranking_results', ['company_profile_id'], unique=False)
    op.create_index(op.f('ix_ranking_results_opportunity_version_id'), 'ranking_results', ['opportunity_version_id'], unique=False)
    op.create_table('structured_extractions',
    sa.Column('opportunity_version_id', sa.UUID(), nullable=False),
    sa.Column('extractor_version', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=255), nullable=True),
    sa.Column('schema_version', sa.String(length=50), nullable=False),
    sa.Column('output_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_status', sa.String(length=50), nullable=False),
    sa.Column('validation_errors_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=18, scale=6), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['opportunity_version_id'], ['opportunity_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_structured_extractions_opportunity_version_id'), 'structured_extractions', ['opportunity_version_id'], unique=False)
    op.create_table('document_parses',
    sa.Column('attachment_id', sa.UUID(), nullable=False),
    sa.Column('parser_kind', sa.String(length=50), nullable=False),
    sa.Column('parser_version', sa.String(length=100), nullable=False),
    sa.Column('text_sha256', sa.String(length=64), nullable=True),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('quality_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['attachment_id'], ['attachments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_parses_attachment_id'), 'document_parses', ['attachment_id'], unique=False)
    op.create_table('notification_events',
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=False),
    sa.Column('delta_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('template_key', sa.String(length=100), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['delta_id'], ['opportunity_deltas.id'], ),
    sa.ForeignKeyConstraint(['opportunity_id'], ['opportunities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dedupe_key')
    )
    op.create_index(op.f('ix_notification_events_opportunity_id'), 'notification_events', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_notification_events_user_id'), 'notification_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_events_user_id'), table_name='notification_events')
    op.drop_index(op.f('ix_notification_events_opportunity_id'), table_name='notification_events')
    op.drop_table('notification_events')
    op.drop_index(op.f('ix_document_parses_attachment_id'), table_name='document_parses')
    op.drop_table('document_parses')
    op.drop_index(op.f('ix_structured_extractions_opportunity_version_id'), table_name='structured_extractions')
    op.drop_table('structured_extractions')
    op.drop_index(op.f('ix_ranking_results_opportunity_version_id'), table_name='ranking_results')
    op.drop_index(op.f('ix_ranking_results_company_profile_id'), table_name='ranking_results')
    op.drop_table('ranking_results')
    op.drop_index(op.f('ix_opportunity_deltas_opportunity_id'), table_name='opportunity_deltas')
    op.drop_table('opportunity_deltas')
    op.drop_index(op.f('ix_eligibility_results_opportunity_version_id'), table_name='eligibility_results')
    op.drop_index(op.f('ix_eligibility_results_company_profile_id'), table_name='eligibility_results')
    op.drop_table('eligibility_results')
    op.drop_index(op.f('ix_attachments_opportunity_version_id'), table_name='attachments')
    op.drop_table('attachments')
    op.drop_index(op.f('ix_watchlists_opportunity_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_raw_records_source_id'), table_name='raw_records')
    op.drop_table('raw_records')
    op.drop_constraint('fk_opportunity_current_version', 'opportunities', type_='foreignkey')
    op.drop_index(op.f('ix_opportunity_versions_opportunity_id'), table_name='opportunity_versions')
    op.drop_table('opportunity_versions')
    op.drop_index(op.f('ix_lifecycle_links_parent_opportunity_id'), table_name='lifecycle_links')
    op.drop_index(op.f('ix_lifecycle_links_child_opportunity_id'), table_name='lifecycle_links')
    op.drop_table('lifecycle_links')
    op.drop_index(op.f('ix_ingest_runs_source_id'), table_name='ingest_runs')
    op.drop_table('ingest_runs')
    op.drop_table('source_registry')
    op.drop_index('ix_opportunities_stage_published', table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_published_at'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_lifecycle_stage'), table_name='opportunities')
    op.drop_index(op.f('ix_opportunities_closes_at'), table_name='opportunities')
    op.drop_table('opportunities')
    op.drop_index('ix_job_failures_dead_lettered_retry', table_name='job_failures')
    op.drop_index(op.f('ix_job_failures_next_retry_at'), table_name='job_failures')
    op.drop_table('job_failures')
    op.drop_index(op.f('ix_company_profiles_owner_user_id'), table_name='company_profiles')
    op.drop_table('company_profiles')
    op.drop_table('audit_events')
    # ### end Alembic commands ###
